[package]
name = "rvfs"
version = "0.1.0"
edition = "2021"
authors = ["Alex Yusiuk thepulticula@gmail.com"]
description = "VFS that focuses on forbitting access malwares"

[[bin]]
name = "rvfs"
path = "src/main.rs"

[dependencies]
fuser = "0.12.0"
tracing = { version = "0.1", default-features = false, features = ["default", "log", "attributes"] }
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
clap = { version = "4.2.1", features = ["derive"] }
libc = "0.2"
tempdir = "0.3.7"
anyhow = "1.0.70"
ctrlc = { version = "3.2.5", features = ["termination"] }